Repository boostcampwm-2024/iOS10-MemorialHouse, pull requests merged in 2024-11, with the labels that each got.

#6 프로젝트 생성 & 초기 설정
  MemorialHouse/MemorialHouse.xcodeproj/project.pbxproj
  MemorialHouse/MemorialHouse.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/AppIcon.appiconset/icon-20@2x.png
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/AppIcon.appiconset/icon-20@3x.png
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/AppIcon.appiconset/icon-29@2x.png
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/AppIcon.appiconset/icon-29@3x.png
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/AppIcon.appiconset/icon-38@2x.png
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/AppIcon.appiconset/icon-38@3x.png
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/AppIcon.appiconset/icon-40@2x.png
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/AppIcon.appiconset/icon-40@3x.png
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/AppIcon.appiconset/icon-60@2x.png
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/AppIcon.appiconset/icon-60@3x.png
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/AppIcon.appiconset/icon-64@2x.png
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/AppIcon.appiconset/icon-64@3x.png
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/AppIcon.appiconset/icon-68@2x.png
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/AppIcon.appiconset/icon-76@2x.png
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/AppIcon.appiconset/icon-83_5@2x.png
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/AppIcon.appiconset/ios-marketing.png
  MemorialHouse/MemorialHouse/Resource/Assets.xcassets/Contents.json
  MemorialHouse/MemorialHouse/Resource/Base.lproj/LaunchScreen.storyboard
  MemorialHouse/MemorialHouse/Resource/Info.plist
  MemorialHouse/MemorialHouse/Source/App/AppDelegate.swift
  MemorialHouse/MemorialHouse/Source/App/SceneDelegate.swift
  MemorialHouse/MemorialHouse/Source/ViewController.swift
Labels: 🧱 Build, ✨ Feature

#9 모듈화된 폴더 구조 수정
  MemorialHouse/MHApplication/MHApplication.xcodeproj/project.pbxproj
  MemorialHouse/MHApplication/MHApplication.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AppIcon.appiconset/icon-20@2x.png
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AppIcon.appiconset/icon-20@3x.png
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AppIcon.appiconset/icon-29@2x.png
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AppIcon.appiconset/icon-29@3x.png
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AppIcon.appiconset/icon-38@2x.png
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AppIcon.appiconset/icon-38@3x.png
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AppIcon.appiconset/icon-40@2x.png
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AppIcon.appiconset/icon-40@3x.png
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AppIcon.appiconset/icon-60@2x.png
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AppIcon.appiconset/icon-60@3x.png
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AppIcon.appiconset/icon-64@2x.png
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AppIcon.appiconset/icon-64@3x.png
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AppIcon.appiconset/icon-68@2x.png
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AppIcon.appiconset/icon-76@2x.png
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AppIcon.appiconset/icon-83_5@2x.png
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AppIcon.appiconset/ios-marketing.png
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/Contents.json
  MemorialHouse/MHApplication/MHApplication/Resource/Base.lproj/LaunchScreen.storyboard
  MemorialHouse/MHApplication/MHApplication/Resource/Info.plist
  MemorialHouse/MHApplication/MHApplication/Source/App/AppDelegate.swift
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHApplication/MHApplication/Source/ViewController.swift
  MemorialHouse/MHCore/MHCore.xcodeproj/project.pbxproj
  MemorialHouse/MHCore/MHCore/Temp.swift
  MemorialHouse/MHData/MHData.xcodeproj/project.pbxproj
  MemorialHouse/MHData/MHData/Temp.swift
  MemorialHouse/MHDomain/MHDomain.xcodeproj/project.pbxproj
  MemorialHouse/MHDomain/MHDomain/Temp.swift
  MemorialHouse/MHPresentation/MHPresentation.xcodeproj/project.pbxproj
  MemorialHouse/MHPresentation/MHPresentation/Temp.swift
  MemorialHouse/MemorialHouse.xcworkspace/contents.xcworkspacedata
Labels: 🧱 Build, 🛠️ Fix

#13 모든 모듈에 SwiftLint 적용
  MemorialHouse/.swiftlint.yml
  MemorialHouse/MHApplication/MHApplication.xcodeproj/project.pbxproj
  MemorialHouse/MHApplication/MHApplication/Source/ViewController.swift
  MemorialHouse/MHCore/MHCore.xcodeproj/project.pbxproj
  MemorialHouse/MHCore/MHCore/Temp.swift
  MemorialHouse/MHData/MHData.xcodeproj/project.pbxproj
  MemorialHouse/MHDomain/MHDomain.xcodeproj/project.pbxproj
  MemorialHouse/MHFoundation/MHFoundation.xcodeproj/project.pbxproj
  MemorialHouse/MHFoundation/MHFoundation/MHFoundation.h
  MemorialHouse/MHPresentation/MHPresentation.xcodeproj/project.pbxproj
  MemorialHouse/MemorialHouse.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 🧱 Build, ✨ Feature

#33 리드미 업데이트
  README.md
Labels: 📋 Docs

#34 리드미 갱신
  README.md
Labels: 📋 Docs

#27 커스텀 앨범 생성
  MemorialHouse/MHApplication/MHApplication.xcodeproj/project.pbxproj
  MemorialHouse/MHPresentation/MHPresentation.xcodeproj/project.pbxproj
  MemorialHouse/MHPresentation/MHPresentation/Resource/Colors.xcassets/PhotoImage.imageset/Camera_duotone.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Colors.xcassets/PhotoImage.imageset/Camera_duotone@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Colors.xcassets/PhotoImage.imageset/Camera_duotone@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Colors.xcassets/PhotoImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/CustomAlbumCollectionViewCell.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/CustomAlbumViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UICollectionViewCell+Identifier.swift
Labels: ✨ Feature, 🎨 Design

#38 HomeViewController 연결 & 네비게이션 바 구현
  MemorialHouse/MHApplication/MHApplication.xcodeproj/project.pbxproj
  MemorialHouse/MHApplication/MHApplication/Source/App/AppDelegate.swift
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHApplication/MHApplication/Source/ViewController.swift
  MemorialHouse/MHCore/MHCore.xcodeproj/project.pbxproj
  MemorialHouse/MHData/MHData.xcodeproj/project.pbxproj
  MemorialHouse/MHDomain/MHDomain.xcodeproj/project.pbxproj
  MemorialHouse/MHFoundation/MHFoundation.xcodeproj/project.pbxproj
  MemorialHouse/MHPresentation/MHPresentation.xcodeproj/project.pbxproj
  MemorialHouse/MHPresentation/MHPresentation/Resource/Colors.xcassets/BaseBackgroundColor.colorset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/PhotoImage.imageset/Camera_duotone.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/PhotoImage.imageset/Camera_duotone@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/PhotoImage.imageset/Camera_duotone@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/PhotoImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/SettingLight.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/SettingLight.imageset/Setting_line_light.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/SettingLight.imageset/Setting_line_light@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/SettingLight.imageset/Setting_line_light@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHNavigationBar.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIFont+Ownglyph.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UILabel+Style.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIView+Anchor.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
Labels: ✨ Feature

#39 책 생성 화면 작성
  MemorialHouse/MHPresentation/MHPresentation/Resource/Colors.xcassets/AccentColor.colorset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Colors.xcassets/MHBeigeColor.colorset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Colors.xcassets/MHBlueColor.colorset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Colors.xcassets/MHBorderColor.colorset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Colors.xcassets/MHGreenColor.colorset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Colors.xcassets/MHOrangeColor.colorset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Colors.xcassets/MHPinkColor.colorset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Colors.xcassets/MHSectionColor.colorset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/BeigeBookImage.imageset/BeigeBookImage.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/BeigeBookImage.imageset/BeigeBookImage@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/BeigeBookImage.imageset/BeigeBookImage@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/BeigeBookImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/BlueBookImage.imageset/BlueBookImage.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/BlueBookImage.imageset/BlueBookImage@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/BlueBookImage.imageset/BlueBookImage@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/BlueBookImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/GreenBookImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/GreenBookImage.imageset/GreenBookImage.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/GreenBookImage.imageset/GreenBookImage@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/GreenBookImage.imageset/GreenBookImage@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OrangeBookImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OrangeBookImage.imageset/OrangeBookImage.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OrangeBookImage.imageset/OrangeBookImage@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OrangeBookImage.imageset/OrangeBookImage@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/PinkBookImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/PinkBookImage.imageset/PingBookImage.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/PinkBookImage.imageset/PingBookImage@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/PinkBookImage.imageset/PingBookImage@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIView+Background.swift
Labels: ✨ Feature, 👷‍♂️ Refactor, 🎨 Design

#40 이미지 편집 뷰 Layout
  MemorialHouse/MHApplication/MHApplication.xcodeproj/project.pbxproj
  MemorialHouse/MHCore/MHCore.xcodeproj/project.pbxproj
  MemorialHouse/MHData/MHData.xcodeproj/project.pbxproj
  MemorialHouse/MHDomain/MHDomain.xcodeproj/project.pbxproj
  MemorialHouse/MHFoundation/MHFoundation.xcodeproj/project.pbxproj
  MemorialHouse/MHPresentation/MHPresentation.xcodeproj/project.pbxproj
  MemorialHouse/MHPresentation/MHPresentation/Resource/Colors.xcassets/CaptionPlaceHolderColor.colorset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Colors.xcassets/DividedLineColor.colorset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/CropImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/CropImage.imageset/Crop.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/CropImage.imageset/Crop@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/CropImage.imageset/Crop@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/DrawImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/DrawImage.imageset/Draw.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/DrawImage.imageset/Draw@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/DrawImage.imageset/Draw@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/RotateImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/RotateImage.imageset/Rotate.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/RotateImage.imageset/Rotate@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/RotateImage.imageset/Rotate@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Source/EditPhoto/EditPhotoViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIView+Anchor.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIView+CustomView.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIViewController+HideKeyboard.swift
Labels: ✨ Feature, 🎨 Design

#43 앱 최초 실행 로직 (Layout X)
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHFoundation/MHFoundation/Constant/Constant.swift
  MemorialHouse/MHPresentation/MHPresentation/Resource/Colors.xcassets/MHTitleColor.colorset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
Labels: ✨ Feature

#44 커스텀 앨범에서 이미지 편집 뷰로 이동
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumCollectionViewCell.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/ViewModel/CustomAlbumViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/ViewModel/LocalPhotoManager.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditPhoto/EditPhotoViewController.swift
Labels: ✨ Feature

#47 BookCover 엔티티 & MHBook 뷰 구현
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHDomain/MHDomain/Entity/BookColor.swift
  MemorialHouse/MHDomain/MHDomain/Entity/BookCover.swift
  MemorialHouse/MHDomain/MHDomain/Temp.swift
  MemorialHouse/MHPresentation/MHPresentation/Resource/Colors.xcassets/TitleColor.colorset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBook.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/BookColor+Image.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UILabel+Style.swift
Labels: ✨ Feature, 🎨 Design

#53 Color Set 이름 수정
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
Labels: 🛠️ Fix

#51 홈 화면 레이아웃 구현 (with CollectionViewFlowLayout)
  .github/workflows/swift.yml
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHDomain/MHDomain/Entity/BookCover.swift
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/BookMakeImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/BookMakeImage.imageset/Subject.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/BookMakeImage.imageset/Subject@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/BookMakeImage.imageset/Subject@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/DotHorizontalImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/DotHorizontalImage.imageset/image 19.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/DotHorizontalImage.imageset/image 19@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/DotHorizontalImage.imageset/image 19@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/DropDownImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/DropDownImage.imageset/Vector 17.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/DropDownImage.imageset/Vector 17@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/DropDownImage.imageset/Vector 17@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/LikeFillImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/LikeFillImage.imageset/Favorite_duotone.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/LikeFillImage.imageset/Favorite_duotone@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/LikeFillImage.imageset/Favorite_duotone@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/SettingLightImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/SettingLightImage.imageset/Setting_line_light.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/SettingLightImage.imageset/Setting_line_light@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/SettingLightImage.imageset/Setting_line_light@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/likeEmptyImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/likeEmptyImage.imageset/Favorite.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/likeEmptyImage.imageset/Favorite@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/likeEmptyImage.imageset/Favorite@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBookCover.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIImage+Resize.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/BookCollectionViewCell.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
Labels: ✨ Feature, 🎨 Design

#54 새로운 책 만들기 - 프리뷰와 입력뷰 연결, 색 버튼 효과, 임시로직 추가
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBookCover.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
Labels: ✨ Feature

#57 런타임 시점에 Constraint를 조절하여 애니메이션 구현하기
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
Labels: ✨ Feature

#62 OSLog 사용을 위한 MHLogger 구현
  MemorialHouse/MHCore/MHCore/MHLogger.swift
  MemorialHouse/MHCore/MHCore/Temp.swift
Labels: ✨ Feature

#60 [Design] 사용자 등록 뷰 디자인
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Common/ViewModelType.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Register/View/RegisterViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Register/ViewModel/RegisterViewModel.swift
Labels: ✨ Feature, 🎨 Design

#66 이미지 Crop 구현 및 TextField 위치 조정, CustomAlbum ViewModel 구조 리팩토링
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/CropImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/CropImage.imageset/Crop.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/CropImage.imageset/Crop@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/CropImage.imageset/Crop@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/ViewModel/CustomAlbumViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditPhoto/EditPhotoViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIView+Anchor.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIView+CustomView.swift
Labels: ✨ Feature, 👷‍♂️ Refactor

#65 홈에서 카테고리 드랍다운 클릭 시 컨텐츠 내용물에 따라 Custom Detent Sheet 보이기
  MemorialHouse/MHFoundation/MHFoundation/Constant/Constant.swift
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/CheckImage.imageset/Checkmark.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/CheckImage.imageset/Checkmark@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/CheckImage.imageset/Checkmark@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/CheckImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryTableViewCell.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBookCover.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHNavigationBar.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditPhoto/EditPhotoViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIBarButtonItem+Create.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UILabel+Style.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UISheetPresentationController+Detent+Identifier.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UITableViewCell+Identifier.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIView+Background.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
Labels: ✨ Feature

#71 책 편집하는 뷰 작성
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/audioButtonImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/audioButtonImage.imageset/audioButtonImage.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/audioButtonImage.imageset/audioButtonImage@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/audioButtonImage.imageset/audioButtonImage@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/imageButtonImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/imageButtonImage.imageset/imageButtonImage.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/imageButtonImage.imageset/imageButtonImage@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/imageButtonImage.imageset/imageButtonImage@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/publishButtonImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/publishButtonImage.imageset/publishButtonImage.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/publishButtonImage.imageset/publishButtonImage@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/publishButtonImage.imageset/publishButtonImage@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/textButtonImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/textButtonImage.imageset/textButtonImage.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/textButtonImage.imageset/textButtonImage@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/textButtonImage.imageset/textButtonImage@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/videoButtonImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/videoButtonImage.imageset/videoButtonImage.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/videoButtonImage.imageset/videoButtonImage@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/videoButtonImage.imageset/videoButtonImage@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditBookViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/ViewModel/EditBookViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditPhoto/EditPhotoViewController.swift
Labels: ✨ Feature, 🎨 Design

#73 홈 화면에서 카테고리 별로 책 필터링하여 보여주기
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHCore/MHCore/DIContainer.swift
  MemorialHouse/MHData/MHData/Repository/DefaultUserHouseRepository.swift
  MemorialHouse/MHData/MHData/Temp.swift
  MemorialHouse/MHDomain/MHDomain.xcodeproj/project.pbxproj
  MemorialHouse/MHDomain/MHDomain/Entity/BookColor.swift
  MemorialHouse/MHDomain/MHDomain/Entity/BookCover.swift
  MemorialHouse/MHDomain/MHDomain/Entity/MemorialHouse.swift
  MemorialHouse/MHDomain/MHDomain/Repository/MemorialHouseRepository.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/DefaultUserHouseUseCase.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/Interface/UserHouseUseCase.swift
  MemorialHouse/MHDomain/MHDomainTests/Stubs/StubMemorialHouseRepository.swift
  MemorialHouse/MHDomain/MHDomainTests/UserHouseUseCaseTest.swift
  MemorialHouse/MHPresentation/MHPresentation.xcodeproj/project.pbxproj
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Common/ViewModelType.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHNavigationBar.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewModelFactory.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Register/View/RegisterViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Register/ViewModel/RegisterViewModel.swift
  MemorialHouse/MHPresentation/MHPresentationTests/HomeViewModelTest.swift
  MemorialHouse/MHPresentation/MHPresentationTests/Stubs/StubFetchMemorialHouseUseCase.swift
Labels: ✨ Feature

#75 CoreData 구축 및 테스트
  MemorialHouse/MHCore/MHCore/MHError.swift
  MemorialHouse/MHData/MHData.xcodeproj/project.pbxproj
  MemorialHouse/MHData/MHData/DTO/BookCoverDTO.swift
  MemorialHouse/MHData/MHData/LocalStorage/BookCoverStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/CoreDataBookCoverStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/CoreDataStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/MemorialHouseModel.xcdatamodeld/MemorialHouseModel.xcdatamodel/contents
  MemorialHouse/MHData/MHData/Repository/DefaultMemorialHouseRepository.swift
  MemorialHouse/MHData/MHData/Repository/LocalBookCoverRepository.swift
  MemorialHouse/MHData/MHDataTests/CoreDataBookCoverStorageTests.swift
  MemorialHouse/MHData/MHDataTests/TestDoubles/MockCoreDataStorage.swift
  MemorialHouse/MHDomain/MHDomain/Entity/BookColor.swift
  MemorialHouse/MHDomain/MHDomain/Repository/BookCoverRepository.swift
Labels: ✨ Feature, ✅ Test

#80 설정 화면 기능 구현
  MemorialHouse/MHApplication/MHApplication/Resource/Info.plist
  MemorialHouse/MHPresentation/MHPresentation/Source/Setting/SettingViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Setting/SettingViewModel.swift
Labels: ✨ Feature

#83 커스텀 앨범 동영상 버전 추가
  MemorialHouse/MHApplication/MHApplication.xcodeproj/project.pbxproj
  MemorialHouse/MHApplication/MHApplication/Resource/Info.plist
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/ViewModel/CustomAlbumViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/ViewModel/LocalPhotoManager.swift
Labels: ✨ Feature

#85 폴라로이드 이미지 커스텀 뷰 만들기
  MemorialHouse/MHFoundation/MHFoundation/Extension/Date+toString.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHPolaroidPhotoView.swift
Labels: ✨ Feature

#87 책 보기 Layout 구현
  MemorialHouse/MHPresentation/MHPresentation/Source/Book/BookViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Book/BookViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/ReadPage/ReadPageViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/ReadPage/ReadPageViewModel.swift
Labels: ✨ Feature

#89 카테고리 시트지에서 편집 기능 & MemorialHouse 엔티티 수정에 따른 Home 로직 수정
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHData/MHData/Repository/DefaultCategoryRepository.swift
  MemorialHouse/MHData/MHData/Repository/DefaultMemorialHouseRepository.swift
  MemorialHouse/MHDomain/MHDomain/Entity/MemorialHouse.swift
  MemorialHouse/MHDomain/MHDomain/Repository/CategoryRepository.swift
  MemorialHouse/MHDomain/MHDomain/Repository/MemorialHouseRepository.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/DefaultCategoryUseCase.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/DefaultMemorialHouseUseCase.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/Interface/CategoryUseCase.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/Interface/MemorialHouseUseCase.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryViewModelFactory.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIAlertController+Initializer.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewModelFactory.swift
Labels: ✨ Feature, 👷‍♂️ Refactor

#82 Book, Page 등 Entity, Storage, Repository, FileManager 생성
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHCore/MHCore/DIContainer.swift
  MemorialHouse/MHCore/MHCore/MHCoreError.swift
  MemorialHouse/MHCore/MHCore/MHDataError.swift
  MemorialHouse/MHCore/MHCore/MHError.swift
  MemorialHouse/MHData/MHData/DTO/BookCoverDTO.swift
  MemorialHouse/MHData/MHData/DTO/BookDTO.swift
  MemorialHouse/MHData/MHData/DTO/MediaDescriptionDTO.swift
  MemorialHouse/MHData/MHData/DTO/PageDTO.swift
  MemorialHouse/MHData/MHData/LocalStorage/BookCoverStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/BookStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/CoreDataBookCoverStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/CoreDataBookStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/MemorialHouseModel.xcdatamodeld/MemorialHouseModel.xcdatamodel/contents
  MemorialHouse/MHData/MHData/LocalStorage/FileManager/MHFileManager.swift
  MemorialHouse/MHData/MHData/LocalStorage/FileStorage.swift
  MemorialHouse/MHData/MHData/Repository/LocalBookRepository.swift
  MemorialHouse/MHData/MHData/Repository/LocalMediaRepository.swift
  MemorialHouse/MHData/MHDataTests/CoreDataBookCoverStorageTests.swift
  MemorialHouse/MHData/MHDataTests/CoreDataBookStorageTests.swift
  MemorialHouse/MHData/MHDataTests/MHFileManagerTests.swift
  MemorialHouse/MHDomain/MHDomain/Entity/Book.swift
  MemorialHouse/MHDomain/MHDomain/Entity/MediaDescription.swift
  MemorialHouse/MHDomain/MHDomain/Entity/MediaType.swift
  MemorialHouse/MHDomain/MHDomain/Entity/Page.swift
  MemorialHouse/MHDomain/MHDomain/Repository/BookRepository.swift
  MemorialHouse/MHDomain/MHDomain/Repository/MediaRepository.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
Labels: ✨ Feature

#92 HomeViewModel 변경에 따른 테스트 코드 수정
  MemorialHouse/MHDomain/MHDomainTests/Stubs/StubMemorialHouseRepository.swift
  MemorialHouse/MHDomain/MHDomainTests/UserHouseUseCaseTest.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewModelFactory.swift
  MemorialHouse/MHPresentation/MHPresentationTests/HomeViewModelTest.swift
Labels: 🛠️ Fix, ✅ Test

#96 리드미 문서화 추가
  README.md
Labels: 📋 Docs

#99 카테고리 CRUD를 CoreData와 연결하여 구현
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHCore/MHCore/MHDataError.swift
  MemorialHouse/MHData/MHData/DTO/BookCategoryDTO.swift
  MemorialHouse/MHData/MHData/DTO/BookCoverDTO.swift
  MemorialHouse/MHData/MHData/DTO/BookDTO.swift
  MemorialHouse/MHData/MHData/DTO/MediaDescriptionDTO.swift
  MemorialHouse/MHData/MHData/DTO/PageDTO.swift
  MemorialHouse/MHData/MHData/LocalStorage/BookCategoryStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/CoreDataBookCategoryStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/CoreDataStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/MemorialHouseModel.xcdatamodeld/MemorialHouseModel.xcdatamodel/contents
  MemorialHouse/MHData/MHData/Repository/DefaultCategoryRepository.swift
  MemorialHouse/MHData/MHData/Repository/LocalBookCategoryRepository.swift
  MemorialHouse/MHData/MHData/Repository/LocalBookCoverRepository.swift
  MemorialHouse/MHData/MHData/Repository/LocalBookRepository.swift
  MemorialHouse/MHData/MHDataTests/CoreDataBookCategoryStorageTests.swift
  MemorialHouse/MHDomain/MHDomain/Entity/BookCategory.swift
  MemorialHouse/MHDomain/MHDomain/Repository/BookCategoryRepository.swift
  MemorialHouse/MHDomain/MHDomain/Repository/BookCoverRepository.swift
  MemorialHouse/MHDomain/MHDomain/Repository/CategoryRepository.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/DefaultCategoryUseCase.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/Interface/BookCategoryUseCase.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/Interface/CategoryUseCase.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/BookCategoryTableViewCell.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/BookCategoryViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/BookCategoryViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/BookCategoryViewModelFactory.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryViewModelFactory.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIAlertController+Initializer.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewModelFactory.swift
Labels: ✨ Feature, ✅ Test

#103 홈화면 책커버 Drag & Drop 구현
  MemorialHouse/MHData/MHData/DTO/BookCoverDTO.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/CoreDataBookCoverStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/MemorialHouseModel.xcdatamodeld/MemorialHouseModel.xcdatamodel/contents
  MemorialHouse/MHData/MHData/Repository/LocalBookCoverRepository.swift
  MemorialHouse/MHData/MHDataTests/CoreDataBookCoverStorageTests.swift
  MemorialHouse/MHData/MHDataTests/MHFileManagerTests.swift
  MemorialHouse/MHDomain/MHDomain/Entity/BookCover.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewModel.swift
Labels: ✨ Feature
