Repository boostcampwm-2024/iOS10-MemorialHouse, pull requests merged in 2024-12, with the labels that each got.

#107 홈 화면 좋아요 버튼 UI & 책커버 업데이트에 따른 코어데이터 저장 로직 구현
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHData/MHData/LocalStorage/BookCoverStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/CoreDataBookStorage.swift
  MemorialHouse/MHData/MHData/Repository/LocalBookCoverRepository.swift
  MemorialHouse/MHData/MHData/Repository/LocalBookRepository.swift
  MemorialHouse/MHData/MHData/Repository/LocalMediaRepository.swift
  MemorialHouse/MHDomain/MHDomain/Repository/BookCoverRepository.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/DefaultBookCategoryUseCase.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/DefaultBookCoverUseCase.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/Interface/BookCoverUseCase.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBookCover.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/BookCollectionViewCell.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewModelFactory.swift
Labels: ✨ Feature

#112 기록소 등록하는 첫 화면 UI 구현
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/RegisterBookImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/RegisterBookImage.imageset/Group 2.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/RegisterBookImage.imageset/Group 2@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/RegisterBookImage.imageset/Group 2@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHRegisterView.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewModel.swift
Labels: 🎨 Design

#114 홈 화면의 책 드랍다운 버튼 클릭 시 UIMenu 로직 구현
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/CoreDataBookCoverStorage.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHRegisterView.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/BookCollectionViewCell.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewModelFactory.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
Labels: ✨ Feature

#113 책 수정 화면 로직 구현
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHCore/MHCore/MHDataError.swift
  MemorialHouse/MHData/MHData/LocalStorage/FileManager/MHFileManager.swift
  MemorialHouse/MHData/MHData/LocalStorage/FileStorage.swift
  MemorialHouse/MHData/MHData/Repository/LocalMediaRepository.swift
  MemorialHouse/MHDomain/MHDomain/Entity/MediaType.swift
  MemorialHouse/MHDomain/MHDomain/Repository/MediaRepository.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/DefaultBookUseCase.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/DefaultMediaUseCase.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/Interface/MediaUseCase.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/CreateBookViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/CreateBookViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHPolaroidPhotoView.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditBookViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/MediaAttachable.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/MediaAttachment.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/MediaAttachmentViewProvider.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/ViewModel/EditBookViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/ViewModel/EditBookViewModelFactory.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/ViewModel/EditPageViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIView+SnapshotImage.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
Labels: ✨ Feature, 👷‍♂️ Refactor

#116 BookCover 생성할 때, 카테고리 설정 로직 구현
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/CreateBookViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/BookCategoryViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/BookCategoryViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/BookCategoryViewModelFactory.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
Labels: ✨ Feature

#121 책 내용 수정시 크래시나는 것 수정
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/MediaAttachment.swift
Labels: 🛠️ Fix

#126 실패 가능한 경우에 대해 Alert 예외처리
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/DefaultMemorialHouseNameUseCase.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Audio/CreateAudioViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCover/View/BookCoverViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCover/ViewModel/CreateBookCoverViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCover/ViewModel/ModifyBookCoverViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/ViewModel/LocalPhotoManager.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIViewController+AuthorizationAlert.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
Labels: 🛠️ Fix

#127 BookCover 이미지 연결
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHData/MHData/DTO/BookCoverDTO.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/CoreDataBookCoverStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/MemorialHouseModel.xcdatamodeld/MemorialHouseModel.xcdatamodel/contents
  MemorialHouse/MHData/MHData/Repository/LocalBookCoverRepository.swift
  MemorialHouse/MHDomain/MHDomain/Entity/BookCover.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCover/View/BookCoverViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCover/ViewModel/CreateBookCoverViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCover/ViewModel/ModifyBookCoverViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBookCover.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditPhoto/EditPhotoViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditPhoto/ViewModel/EditPhotoViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditPhoto/ViewModel/EditPhotoViewModelFactory.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/BookCollectionViewCell.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewModel.swift
Labels: ✨ Feature, 👷‍♂️ Refactor

#129 EditPage에서 이미지 추가하는 기능 구현
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditBookViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/ViewModel/EditBookViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/ViewModel/EditPageViewModel.swift
Labels: ✨ Feature, 👷‍♂️ Refactor

#131 책 읽기 페이지에서 책 수정 기능 구현
  MemorialHouse/MHPresentation/MHPresentation/Source/Book/View/BookViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Book/ViewModel/BookViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCover/View/BookCoverViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditBookViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/ViewModel/EditBookViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/ReadPage/View/ReadPageViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/ReadPage/ViewModel/ReadPageViewModel.swift
Labels: ✨ Feature, 👷‍♂️ Refactor

#132 책 생성 & 페이지 볼 때 비디오 저장 및 불러오기 구현
  MemorialHouse/MHData/MHData/LocalStorage/FileManager/MHFileManager.swift
  MemorialHouse/MHData/MHData/Repository/LocalMediaRepository.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/DefaultMediaUseCase.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCover/View/BookCoverViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Category/BookCategoryViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/ViewModel/LocalPhotoManager.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHVideoView.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditBookViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/MediaAttachmentViewProvider.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditPhoto/EditPhotoViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditVideo/EditVideoViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIViewController+AudioSession.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIViewController+ErrorAlert.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/ReadPage/View/ReadPageViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/ReadPage/ViewModel/ReadPageViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
Labels: ✨ Feature

#122 [Audio] 페이지에 오디오 플레이어 연결
  MemorialHouse/MHApplication/MHApplication.xcodeproj/project.pbxproj
  MemorialHouse/MHApplication/MHApplication/Resource/Info.plist
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHData/MHData/LocalStorage/FileManager/MHFileManager.swift
  MemorialHouse/MHData/MHData/LocalStorage/FileStorage.swift
  MemorialHouse/MHData/MHData/Repository/LocalMediaRepository.swift
  MemorialHouse/MHDomain/MHDomain/Repository/MediaRepository.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/DefaultMediaUseCase.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/Interface/MediaUseCase.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Audio/View/CreateAudioViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Audio/ViewModel/CreateAudioViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Audio/ViewModel/CreateAudioViewModelFactory.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Audio/CreateAudioViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/Enum/AudioPlayState.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/ViewModel/AudioPlayerViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditBookViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/ViewModel/EditBookViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/ReadPage/View/ReadPageViewController.swift
Labels: ✨ Feature, 🎨 Design

#134 MVP 완성에 따른 리드미 업데이트
  README.md
Labels: 📋 Docs

#139 프로젝트 소개 리드미 (찐찐막)
  README.md
Labels: 📋 Docs

#140 리드미 업데이트 (찐찐찐막)
  README.md
Labels: 📋 Docs

#141 Hotfix/audio
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/DefaultMediaUseCase.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/Interface/MediaUseCase.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Audio/View/CreateAudioViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Audio/ViewModel/CreateAudioViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/ViewModel/EditBookViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/ViewModel/EditBookViewModelFactory.swift
Labels: 🛠️ Fix

#146 EditPage 자잘한 버그수정 (높이 이슈, 페이지 추가시 스크롤)
  MemorialHouse/MHDomain/MHDomain/Entity/MediaType.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditBookViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/MediaAttachment.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/MediaAttachmentViewProvider.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/ViewModel/EditBookViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/ViewModel/EditPageViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/MediaType+height.swift
Labels: 🛠️ Fix

#148 [Hotfix/audio] 오디오 중단 & 재시작 할때의 음성 표시 바 수정
  MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Audio/View/CreateAudioViewController.swift
Labels: 🛠️ Fix

#150 BookCoverTitle과 BookTitle 동기화 오류 해결
  MemorialHouse/MHPresentation/MHPresentation/Source/Book/View/BookViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Book/ViewModel/BookViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Book/ViewModel/BookViewModelFactory.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCover/View/BookCoverViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditBookViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/ViewModel/EditBookViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/ViewModel/EditBookViewModelFactory.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/View/HomeViewController.swift
Labels: 🛠️ Fix, 👷‍♂️ Refactor

#152 Release/0.6.0
  MemorialHouse/MHApplication/MHApplication.xcodeproj/project.pbxproj
  MemorialHouse/MHData/MHDataTests/CoreDataBookCoverStorageTests.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditBookViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditPhoto/EditPhotoViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/View/HomeViewController.swift
  MemorialHouse/MHPresentation/MHPresentationTests/HomeViewModelTest.swift
  MemorialHouse/MHPresentation/MHPresentationTests/TestDoubles/StubBookCoverUseCase.swift
Labels: 🛠️ Fix, 🎯 Release

#156 TextView에서 CustomView Drag-Drop시 Preview가 제대로 나오지 않던 문제 수정
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/ViewModel/EditPageViewModel.swift
Labels: 🛠️ Fix

#158 앱 시작 시 온보딩 화면 UI & 로직 구현
  MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OnboardingFourImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OnboardingFourImage.imageset/onboarding4.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OnboardingFourImage.imageset/onboarding4@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OnboardingFourImage.imageset/onboarding4@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OnboardingOneImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OnboardingOneImage.imageset/onboarding1.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OnboardingOneImage.imageset/onboarding1@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OnboardingOneImage.imageset/onboarding1@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OnboardingThreeImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OnboardingThreeImage.imageset/onboarding3.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OnboardingThreeImage.imageset/onboarding3@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OnboardingThreeImage.imageset/onboarding3@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OnboardingTwoImage.imageset/Contents.json
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OnboardingTwoImage.imageset/onboarding2.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OnboardingTwoImage.imageset/onboarding2@2x.png
  MemorialHouse/MHPresentation/MHPresentation/Resource/Images.xcassets/OnboardingTwoImage.imageset/onboarding2@3x.png
  MemorialHouse/MHPresentation/MHPresentation/Source/Onboarding/OnboardingPageViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Onboarding/OnboardingViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/ReadPage/View/ReadPageViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Register/View/RegisterViewController.swift
Labels: ✨ Feature

#160 Release 1.0.0 배포
  MemorialHouse/MHApplication/MHApplication.xcodeproj/project.pbxproj
Labels: 🎯 Release

#162 앱 심사 이슈 반영 - 미디어 접근 문구 + 제한된 접근 사진 추가 버튼, NavigationBar 안 보이는 이슈
  MemorialHouse/MHApplication/MHApplication.xcodeproj/project.pbxproj
  MemorialHouse/MHApplication/MHApplication/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  MemorialHouse/MHApplication/MHApplication/Resource/Info.plist
  MemorialHouse/MHCore/MHCore.xcodeproj/project.pbxproj
  MemorialHouse/MHData/MHData.xcodeproj/project.pbxproj
  MemorialHouse/MHDomain/MHDomain.xcodeproj/project.pbxproj
  MemorialHouse/MHFoundation/MHFoundation.xcodeproj/project.pbxproj
  MemorialHouse/MHPresentation/MHPresentation.xcodeproj/project.pbxproj
  MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBookCover.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Onboarding/OnboardingViewController.swift
Labels: 🧱 Build, 🛠️ Fix, 👷‍♂️ Refactor
