Repository boostcampwm-2024/iOS10-MemorialHouse, pull requests merged in 2025-03, with the labels that each got.

#175 Combine Subject의 Thread와 관련한 문제 해결
  MemorialHouse/MHPresentation/MHPresentation/Source/Register/ViewModel/RegisterViewModel.swift
Labels: 🛠️ Fix

#176 UserDefaults, CoreData, FileManager 비동기 처리 리팩토링 및 불필요한 async/await 키워드 제거
  MemorialHouse/MHData/MHData/LocalStorage/BookCategoryStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/BookCoverStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/BookStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/CoreDataBookCategoryStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/CoreDataBookCoverStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/CoreDataBookStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/CoreData/CoreDataStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/FileManager/MHFileManager.swift
  MemorialHouse/MHData/MHData/LocalStorage/FileStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/MemorialHouseNameStorage.swift
  MemorialHouse/MHData/MHData/LocalStorage/UserDefaults/UserDefaultsMemorialHouseNameStorage.swift
  MemorialHouse/MHData/MHData/Repository/LocalBookCategoryRepository.swift
  MemorialHouse/MHData/MHData/Repository/LocalBookCoverRepository.swift
  MemorialHouse/MHData/MHData/Repository/LocalBookRepository.swift
  MemorialHouse/MHData/MHData/Repository/LocalMediaRepository.swift
  MemorialHouse/MHData/MHData/Repository/LocalMemorialHouseNameRepository.swift
  MemorialHouse/MHDomain/MHDomain/Repository/BookCategoryRepository.swift
  MemorialHouse/MHDomain/MHDomain/Repository/BookCoverRepository.swift
  MemorialHouse/MHDomain/MHDomain/Repository/BookRepository.swift
  MemorialHouse/MHDomain/MHDomain/Repository/MediaRepository.swift
  MemorialHouse/MHDomain/MHDomain/Repository/MemorialHouseNameRepository.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/DefaultBookCategoryUseCase.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/DefaultBookCoverUseCase.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/DefaultBookUseCase.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/DefaultMediaUseCase.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/DefaultMemorialHouseNameUseCase.swift
  MemorialHouse/MHDomain/MHDomain/UseCase/Interface/MemorialHouseNameUseCase.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Audio/ViewModel/CreateAudioViewModelFactory.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Book/View/BookViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Book/ViewModel/BookViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCover/ViewModel/ModifyBookCoverViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/ViewModel/HomeViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Register/View/RegisterViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Register/ViewModel/RegisterViewModel.swift
Labels: 👷‍♂️ Refactor

#177 버튼 중복 클릭에 의해 사용자 경험이 저하되는 문제해결
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCover/ViewModel/CreateBookCoverViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/BookCover/ViewModel/ModifyBookCoverViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/ViewModel/EditBookViewModel.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/View/HomeViewController.swift
  MemorialHouse/MHPresentation/MHPresentation/Source/Home/ViewModel/HomeViewModel.swift
Labels: 🛠️ Fix

#179 Release 1.1.0
  MemorialHouse/MHApplication/MHApplication.xcodeproj/project.pbxproj
Labels: 🎯 Release
